CREATE SCHEMA IF NOT EXISTS library;

USE library;

DROP TABLE IF EXISTS author;
CREATE TABLE author (
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) DEFAULT NULL,
  last_name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
);
