/*
 * This file is generated by jOOQ.
 */
package com.example.codegen;


import com.example.codegen.tables.Author;


/**
 * Convenience access to all tables in library.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
